use serde_json::{json, Value};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};

pub const WORKSPACE_PROFILE_DIRNAME: &str = "browser-workspace";
pub const WORKSPACE_EXTENSION_DIRNAME: &str = "browser-workspace-extension";
pub const WORKSPACE_ENDPOINT: &str = "ws://127.0.0.1:18766";

pub fn app_data_root() -> PathBuf {
    dirs::data_dir()
        .unwrap_or_else(|| std::env::temp_dir())
        .join("science.wisp-science")
}

pub fn profile_dir() -> PathBuf {
    app_data_root().join(WORKSPACE_PROFILE_DIRNAME)
}

pub fn extension_copy_dir() -> PathBuf {
    app_data_root().join(WORKSPACE_EXTENSION_DIRNAME)
}

pub fn chrome_executable() -> Result<PathBuf, String> {
    let candidates = [
        PathBuf::from(r"C:\Program Files\Google\Chrome\Application\chrome.exe"),
        PathBuf::from(r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"),
    ];
    for path in candidates {
        if path.is_file() {
            return Ok(path);
        }
    }
    which::which("chrome")
        .or_else(|_| which::which("google-chrome"))
        .map_err(|_| {
            "Chrome executable not found at C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
                .into()
        })
}

pub fn materialize_extension(source: &Path) -> Result<PathBuf, String> {
    if !source.join("manifest.json").is_file() {
        return Err("bundled browser-extension is missing manifest.json".into());
    }
    let dest = extension_copy_dir();
    if dest.exists() {
        fs::remove_dir_all(&dest).map_err(|error| format!("clear workspace extension: {error}"))?;
    }
    copy_dir(source, &dest)?;
    let config = r#"// Generated by Wisp for the independent workspace Chrome profile.
var WISP_BRIDGE_CONFIG = {
  session: "workspace",
  endpoint: "ws://127.0.0.1:18766"
};
"#;
    fs::write(dest.join("session_config.js"), config)
        .map_err(|error| format!("write workspace session_config.js: {error}"))?;
    Ok(dest)
}

fn copy_dir(src: &Path, dest: &Path) -> Result<(), String> {
    fs::create_dir_all(dest).map_err(|error| format!("create {dest:?}: {error}"))?;
    for entry in fs::read_dir(src).map_err(|error| format!("read {src:?}: {error}"))? {
        let entry = entry.map_err(|error| error.to_string())?;
        let from = entry.path();
        let to = dest.join(entry.file_name());
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('_') || name.ends_with(".test.mjs") {
            continue;
        }
        if from.is_dir() {
            copy_dir(&from, &to)?;
        } else {
            fs::copy(&from, &to).map_err(|error| format!("copy {from:?}: {error}"))?;
        }
    }
    Ok(())
}

pub fn launch_chrome(profile: &Path, extension: &Path) -> Result<Child, String> {
    let chrome = chrome_executable()?;
    fs::create_dir_all(profile).map_err(|error| format!("create workspace profile: {error}"))?;
    let mut command = Command::new(chrome);
    command
        .arg(format!("--user-data-dir={}", profile.display()))
        .arg(format!("--load-extension={}", extension.display()))
        .arg("--no-first-run")
        .arg("--no-default-browser-check")
        .arg("--new-window")
        .arg("about:blank")
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    command
        .spawn()
        .map_err(|error| format!("failed to launch workspace Chrome: {error}"))
}

pub fn status_json(connected: bool, child_running: bool) -> Value {
    json!({
        "session": "workspace",
        "connected": connected,
        "process_running": child_running,
        "profile_dir": profile_dir().display().to_string(),
        "extension_dir": extension_copy_dir().display().to_string(),
        "endpoint": WORKSPACE_ENDPOINT,
        "chrome": chrome_executable().ok().map(|path| path.display().to_string()),
    })
}

